<?php

/**
 * @file
 *
 * Install, deployment (update), and uninstall hooks for this module.
 */

// The autoloader is in the .module file, which is not automatically present
// for Drupal 7.
module_load_include('module', 'realistic_dummy_content_api');
use Drupal\realistic_dummy_content_api\Framework\Framework;

/**
 * Implements hook_uninstall().
 */
function realistic_dummy_content_api_uninstall() {
  // This is an internal variable used by tests to avoid using random
  // images. This is necessary in order to test that the image replacement
  // happens correctly.
  Framework::instance()->variableDel('realistic_dummy_content_api_rand');
}

/**
 * Add fruit to the default configuration for example.module.
 */
function realistic_dummy_content_api_update_8001() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('realistic_dummy_content_api');
  $config->set('realistic_dummy_content_api_rand', 1);
  $config->save(TRUE);
}
